name: CI

on:
  push:
    branches:
    - '*'
    - '!gh-pages'
    tags:
    - '*'
  pull_request:
    branches:
    - '*'
    - '!gh-pages'

jobs:
  deploy:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.105'
    - run: dotnet restore
    - working-directory: Authgear.Xamarin
      run: dotnet format --verify-no-changes
    - uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '17.0'
    - run: msbuild Authgear.Xamarin/Authgear.Xamarin.csproj
    - working-directory: UnitTest
      run: dotnet test
    - uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install docfx
      if: ${{ github.ref == 'refs/heads/main' }}
    - working-directory: Documentation
      run: docfx docfx.json
      if: ${{ github.ref == 'refs/heads/main' }}
    - name: Deploy docs to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: Documentation/_site
  pack:
    runs-on: windows-2022
    needs: ["deploy"]
    if: startsWith(github.ref, 'refs/tags') && !startsWith(github.ref, 'refs/tags/staging-')
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.105'
    - run: dotnet restore
    - uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '17.0'
    - run: msbuild Authgear.Xamarin/Authgear.Xamarin.csproj /t:pack /p:Configuration=Release
    - uses: actions/upload-artifact@v3
      with:
        name: nupkg
        path: Authgear.Xamarin/bin/Release/Authgear.Xamarin.*.nupkg
        retention-days: 5

